### ISSUE TITLE
بحاجة لإضافة قائمة بالكلمات المعتمدة في الصفحة الرئيسيّة

### ISSUE THREAD

**Issue by abdulrahman-alhemeiri** [alhadhrami/ArabicOOPTerms#6]

**Comment by alhadhrami** [comment]
https://github.com/alhadhrami/ArabicOOPTerms/pull/7

**Comment by abdulrahman-alhemeiri** [comment]
<p dir="rtl" align="right">
تم هنا  <a href="https://github.com/alhadhrami/ArabicOOPTerms/pull/7">7#</a>
</p>
